language: android
jdk:
  - oraclejdk7
sudo: false
env:
  global:
    - secure: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4GIgqXdPOkehPwITfExrH+NrT q3uJlNS0ZWeEd/QCVLayVGTScAzYrJZcC3hw09rHe9fQv0VRtvfGN1O4Zh4Q1cTI 1DBswD5F68SFxWN/DbPafCmu+wuCEr767iCqw8JwxynChyRYMOcdf22VQz8QUbfb CKwHayMOtCC8XiPLBQIDAQAB"
android:
  components:
    - build-tools-22.0.0
    - android-22
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-19
before_install:
    # Gradle
    - wget -q http://services.gradle.org/distributions/gradle-2.10-all.zip
    - unzip -q gradle-2.10-all.zip
    - export GRADLE_HOME=$PWD/gradle-2.10
    - export PATH=$GRADLE_HOME/bin:$PATH
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
