language: android
jdk:
  - oraclejdk7
sudo: false
android:
  components:
    - build-tools-22.0.0
    - android-22
    - extra-android-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android
before_install:
    # Gradle
    - wget -q http://services.gradle.org/distributions/gradle-2.10-all.zip
    - unzip -q gradle-2.10-all.zip
    - export GRADLE_HOME=$PWD/gradle-2.10
    - export PATH=$GRADLE_HOME/bin:$PATH
    - curl https://www.jpm4j.org/install/script | sh
    - jpm install com.codacy:codacy-coverage-reporter:assembly
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
#script:
#
after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- gradle cobertura #//coveralls
  - codacy-coverage-reporter -l Java -r coverage.xml

